### ISSUE TITLE
Lync Connector questions

### ISSUE THREAD

**Issue by alexiszp** [Microsoft/MIMPowerShellConnectors#12]
Hello!
I have a problem with some points in your Lync script.
1. You have an expression CustomExpression(IIF(Eq(xSkypeEntitlement,"Active"),"true","false" → Enabled. Correctly I understand, what if in MV attribute xSkypeEntitlement will be something like "Active", parameter "Enabled" will get "true" value and user will get Skype access? If this attribute will be empty, what will happenes? It can be empty, for example, for fired users.
2. In my first configuration I don't use this attribute, but I have many disabled users and this script want to give all this users acces to Skype. Now I have added this attribute and sync flow for it, but Lync MA anyway want to give acces for this users to Skype. But if I correctly understand conditions for rule from question 1 it must not be happened.
3. Maybe it would be better to make this rule pool1.contoso.com → RegistrarPool only to initial flow? If I have 2 pools, I can provision them to first one and later administrator will move users to second if needed. And my sync rule will not update this attribute after provisioning.
Thank for you work and help!

**Comment by NileshGhodekar** [comment]
First, the sample sync rule listed in the Wiki is not part of the Lync connector, it's your **business logic** and you should configure to meet any specific use cases that you want to implement.  You should think of any custom connector as any other out-of-the-box connector, e.g. AD MA, if it helps conceptualise better. You'd probably able to answer your own questions if you consider Lync MA = AD MA.

#1 - This expression will not control whether account is provisioned or no. It will only control whether the account is enabled or disabled. In this specific example, if the value is not "Active", account will be disabled.

#2 - The configuration to provision an account or not, is a separate configuration on Sync Rule. It's called "Create Resource In External System". You should control that as per your use case. In the example, it's controlled by "Outbound System Scoping Filter" which in the example says if the user has an AD account, give it an Lync account as well. You can modify as per your business requirement. e.g. you could use xSkypeEntitlement. In fact, for one of my customer, I'm using that attribute and hence its a string attribute instead of a Boolean attribute as it just not used to control whether account is enabled/disabled, but also drives actual entitlement. 

#3 - Again it's up to you and how you want FIM to drive or not drive source of authority.
